// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/Ghaarp/chat-server/internal/repository.RepoConverter -o repo_converter_minimock.go -n RepoConverterMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	repoModel "github.com/Ghaarp/chat-server/internal/repository/chat/model"
	serviceModel "github.com/Ghaarp/chat-server/internal/service/chat/model"
	"github.com/gojuno/minimock/v3"
)

// RepoConverterMock implements mm_repository.RepoConverter
type RepoConverterMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcToCreateRequest          func(req *serviceModel.CreateRequest) (cp1 *repoModel.CreateRequest)
	funcToCreateRequestOrigin    string
	inspectFuncToCreateRequest   func(req *serviceModel.CreateRequest)
	afterToCreateRequestCounter  uint64
	beforeToCreateRequestCounter uint64
	ToCreateRequestMock          mRepoConverterMockToCreateRequest

	funcToSendMessageRequest          func(req *serviceModel.SendMessageRequest) (sp1 *repoModel.SendMessageRequest)
	funcToSendMessageRequestOrigin    string
	inspectFuncToSendMessageRequest   func(req *serviceModel.SendMessageRequest)
	afterToSendMessageRequestCounter  uint64
	beforeToSendMessageRequestCounter uint64
	ToSendMessageRequestMock          mRepoConverterMockToSendMessageRequest
}

// NewRepoConverterMock returns a mock for mm_repository.RepoConverter
func NewRepoConverterMock(t minimock.Tester) *RepoConverterMock {
	m := &RepoConverterMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ToCreateRequestMock = mRepoConverterMockToCreateRequest{mock: m}
	m.ToCreateRequestMock.callArgs = []*RepoConverterMockToCreateRequestParams{}

	m.ToSendMessageRequestMock = mRepoConverterMockToSendMessageRequest{mock: m}
	m.ToSendMessageRequestMock.callArgs = []*RepoConverterMockToSendMessageRequestParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepoConverterMockToCreateRequest struct {
	optional           bool
	mock               *RepoConverterMock
	defaultExpectation *RepoConverterMockToCreateRequestExpectation
	expectations       []*RepoConverterMockToCreateRequestExpectation

	callArgs []*RepoConverterMockToCreateRequestParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepoConverterMockToCreateRequestExpectation specifies expectation struct of the RepoConverter.ToCreateRequest
type RepoConverterMockToCreateRequestExpectation struct {
	mock               *RepoConverterMock
	params             *RepoConverterMockToCreateRequestParams
	paramPtrs          *RepoConverterMockToCreateRequestParamPtrs
	expectationOrigins RepoConverterMockToCreateRequestExpectationOrigins
	results            *RepoConverterMockToCreateRequestResults
	returnOrigin       string
	Counter            uint64
}

// RepoConverterMockToCreateRequestParams contains parameters of the RepoConverter.ToCreateRequest
type RepoConverterMockToCreateRequestParams struct {
	req *serviceModel.CreateRequest
}

// RepoConverterMockToCreateRequestParamPtrs contains pointers to parameters of the RepoConverter.ToCreateRequest
type RepoConverterMockToCreateRequestParamPtrs struct {
	req **serviceModel.CreateRequest
}

// RepoConverterMockToCreateRequestResults contains results of the RepoConverter.ToCreateRequest
type RepoConverterMockToCreateRequestResults struct {
	cp1 *repoModel.CreateRequest
}

// RepoConverterMockToCreateRequestOrigins contains origins of expectations of the RepoConverter.ToCreateRequest
type RepoConverterMockToCreateRequestExpectationOrigins struct {
	origin    string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) Optional() *mRepoConverterMockToCreateRequest {
	mmToCreateRequest.optional = true
	return mmToCreateRequest
}

// Expect sets up expected params for RepoConverter.ToCreateRequest
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) Expect(req *serviceModel.CreateRequest) *mRepoConverterMockToCreateRequest {
	if mmToCreateRequest.mock.funcToCreateRequest != nil {
		mmToCreateRequest.mock.t.Fatalf("RepoConverterMock.ToCreateRequest mock is already set by Set")
	}

	if mmToCreateRequest.defaultExpectation == nil {
		mmToCreateRequest.defaultExpectation = &RepoConverterMockToCreateRequestExpectation{}
	}

	if mmToCreateRequest.defaultExpectation.paramPtrs != nil {
		mmToCreateRequest.mock.t.Fatalf("RepoConverterMock.ToCreateRequest mock is already set by ExpectParams functions")
	}

	mmToCreateRequest.defaultExpectation.params = &RepoConverterMockToCreateRequestParams{req}
	mmToCreateRequest.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmToCreateRequest.expectations {
		if minimock.Equal(e.params, mmToCreateRequest.defaultExpectation.params) {
			mmToCreateRequest.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmToCreateRequest.defaultExpectation.params)
		}
	}

	return mmToCreateRequest
}

// ExpectReqParam1 sets up expected param req for RepoConverter.ToCreateRequest
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) ExpectReqParam1(req *serviceModel.CreateRequest) *mRepoConverterMockToCreateRequest {
	if mmToCreateRequest.mock.funcToCreateRequest != nil {
		mmToCreateRequest.mock.t.Fatalf("RepoConverterMock.ToCreateRequest mock is already set by Set")
	}

	if mmToCreateRequest.defaultExpectation == nil {
		mmToCreateRequest.defaultExpectation = &RepoConverterMockToCreateRequestExpectation{}
	}

	if mmToCreateRequest.defaultExpectation.params != nil {
		mmToCreateRequest.mock.t.Fatalf("RepoConverterMock.ToCreateRequest mock is already set by Expect")
	}

	if mmToCreateRequest.defaultExpectation.paramPtrs == nil {
		mmToCreateRequest.defaultExpectation.paramPtrs = &RepoConverterMockToCreateRequestParamPtrs{}
	}
	mmToCreateRequest.defaultExpectation.paramPtrs.req = &req
	mmToCreateRequest.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmToCreateRequest
}

// Inspect accepts an inspector function that has same arguments as the RepoConverter.ToCreateRequest
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) Inspect(f func(req *serviceModel.CreateRequest)) *mRepoConverterMockToCreateRequest {
	if mmToCreateRequest.mock.inspectFuncToCreateRequest != nil {
		mmToCreateRequest.mock.t.Fatalf("Inspect function is already set for RepoConverterMock.ToCreateRequest")
	}

	mmToCreateRequest.mock.inspectFuncToCreateRequest = f

	return mmToCreateRequest
}

// Return sets up results that will be returned by RepoConverter.ToCreateRequest
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) Return(cp1 *repoModel.CreateRequest) *RepoConverterMock {
	if mmToCreateRequest.mock.funcToCreateRequest != nil {
		mmToCreateRequest.mock.t.Fatalf("RepoConverterMock.ToCreateRequest mock is already set by Set")
	}

	if mmToCreateRequest.defaultExpectation == nil {
		mmToCreateRequest.defaultExpectation = &RepoConverterMockToCreateRequestExpectation{mock: mmToCreateRequest.mock}
	}
	mmToCreateRequest.defaultExpectation.results = &RepoConverterMockToCreateRequestResults{cp1}
	mmToCreateRequest.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmToCreateRequest.mock
}

// Set uses given function f to mock the RepoConverter.ToCreateRequest method
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) Set(f func(req *serviceModel.CreateRequest) (cp1 *repoModel.CreateRequest)) *RepoConverterMock {
	if mmToCreateRequest.defaultExpectation != nil {
		mmToCreateRequest.mock.t.Fatalf("Default expectation is already set for the RepoConverter.ToCreateRequest method")
	}

	if len(mmToCreateRequest.expectations) > 0 {
		mmToCreateRequest.mock.t.Fatalf("Some expectations are already set for the RepoConverter.ToCreateRequest method")
	}

	mmToCreateRequest.mock.funcToCreateRequest = f
	mmToCreateRequest.mock.funcToCreateRequestOrigin = minimock.CallerInfo(1)
	return mmToCreateRequest.mock
}

// When sets expectation for the RepoConverter.ToCreateRequest which will trigger the result defined by the following
// Then helper
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) When(req *serviceModel.CreateRequest) *RepoConverterMockToCreateRequestExpectation {
	if mmToCreateRequest.mock.funcToCreateRequest != nil {
		mmToCreateRequest.mock.t.Fatalf("RepoConverterMock.ToCreateRequest mock is already set by Set")
	}

	expectation := &RepoConverterMockToCreateRequestExpectation{
		mock:               mmToCreateRequest.mock,
		params:             &RepoConverterMockToCreateRequestParams{req},
		expectationOrigins: RepoConverterMockToCreateRequestExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmToCreateRequest.expectations = append(mmToCreateRequest.expectations, expectation)
	return expectation
}

// Then sets up RepoConverter.ToCreateRequest return parameters for the expectation previously defined by the When method
func (e *RepoConverterMockToCreateRequestExpectation) Then(cp1 *repoModel.CreateRequest) *RepoConverterMock {
	e.results = &RepoConverterMockToCreateRequestResults{cp1}
	return e.mock
}

// Times sets number of times RepoConverter.ToCreateRequest should be invoked
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) Times(n uint64) *mRepoConverterMockToCreateRequest {
	if n == 0 {
		mmToCreateRequest.mock.t.Fatalf("Times of RepoConverterMock.ToCreateRequest mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmToCreateRequest.expectedInvocations, n)
	mmToCreateRequest.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmToCreateRequest
}

func (mmToCreateRequest *mRepoConverterMockToCreateRequest) invocationsDone() bool {
	if len(mmToCreateRequest.expectations) == 0 && mmToCreateRequest.defaultExpectation == nil && mmToCreateRequest.mock.funcToCreateRequest == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmToCreateRequest.mock.afterToCreateRequestCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmToCreateRequest.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ToCreateRequest implements mm_repository.RepoConverter
func (mmToCreateRequest *RepoConverterMock) ToCreateRequest(req *serviceModel.CreateRequest) (cp1 *repoModel.CreateRequest) {
	mm_atomic.AddUint64(&mmToCreateRequest.beforeToCreateRequestCounter, 1)
	defer mm_atomic.AddUint64(&mmToCreateRequest.afterToCreateRequestCounter, 1)

	mmToCreateRequest.t.Helper()

	if mmToCreateRequest.inspectFuncToCreateRequest != nil {
		mmToCreateRequest.inspectFuncToCreateRequest(req)
	}

	mm_params := RepoConverterMockToCreateRequestParams{req}

	// Record call args
	mmToCreateRequest.ToCreateRequestMock.mutex.Lock()
	mmToCreateRequest.ToCreateRequestMock.callArgs = append(mmToCreateRequest.ToCreateRequestMock.callArgs, &mm_params)
	mmToCreateRequest.ToCreateRequestMock.mutex.Unlock()

	for _, e := range mmToCreateRequest.ToCreateRequestMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1
		}
	}

	if mmToCreateRequest.ToCreateRequestMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmToCreateRequest.ToCreateRequestMock.defaultExpectation.Counter, 1)
		mm_want := mmToCreateRequest.ToCreateRequestMock.defaultExpectation.params
		mm_want_ptrs := mmToCreateRequest.ToCreateRequestMock.defaultExpectation.paramPtrs

		mm_got := RepoConverterMockToCreateRequestParams{req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmToCreateRequest.t.Errorf("RepoConverterMock.ToCreateRequest got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmToCreateRequest.ToCreateRequestMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmToCreateRequest.t.Errorf("RepoConverterMock.ToCreateRequest got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmToCreateRequest.ToCreateRequestMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmToCreateRequest.ToCreateRequestMock.defaultExpectation.results
		if mm_results == nil {
			mmToCreateRequest.t.Fatal("No results are set for the RepoConverterMock.ToCreateRequest")
		}
		return (*mm_results).cp1
	}
	if mmToCreateRequest.funcToCreateRequest != nil {
		return mmToCreateRequest.funcToCreateRequest(req)
	}
	mmToCreateRequest.t.Fatalf("Unexpected call to RepoConverterMock.ToCreateRequest. %v", req)
	return
}

// ToCreateRequestAfterCounter returns a count of finished RepoConverterMock.ToCreateRequest invocations
func (mmToCreateRequest *RepoConverterMock) ToCreateRequestAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmToCreateRequest.afterToCreateRequestCounter)
}

// ToCreateRequestBeforeCounter returns a count of RepoConverterMock.ToCreateRequest invocations
func (mmToCreateRequest *RepoConverterMock) ToCreateRequestBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmToCreateRequest.beforeToCreateRequestCounter)
}

// Calls returns a list of arguments used in each call to RepoConverterMock.ToCreateRequest.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmToCreateRequest *mRepoConverterMockToCreateRequest) Calls() []*RepoConverterMockToCreateRequestParams {
	mmToCreateRequest.mutex.RLock()

	argCopy := make([]*RepoConverterMockToCreateRequestParams, len(mmToCreateRequest.callArgs))
	copy(argCopy, mmToCreateRequest.callArgs)

	mmToCreateRequest.mutex.RUnlock()

	return argCopy
}

// MinimockToCreateRequestDone returns true if the count of the ToCreateRequest invocations corresponds
// the number of defined expectations
func (m *RepoConverterMock) MinimockToCreateRequestDone() bool {
	if m.ToCreateRequestMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ToCreateRequestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ToCreateRequestMock.invocationsDone()
}

// MinimockToCreateRequestInspect logs each unmet expectation
func (m *RepoConverterMock) MinimockToCreateRequestInspect() {
	for _, e := range m.ToCreateRequestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoConverterMock.ToCreateRequest at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterToCreateRequestCounter := mm_atomic.LoadUint64(&m.afterToCreateRequestCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ToCreateRequestMock.defaultExpectation != nil && afterToCreateRequestCounter < 1 {
		if m.ToCreateRequestMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepoConverterMock.ToCreateRequest at\n%s", m.ToCreateRequestMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepoConverterMock.ToCreateRequest at\n%s with params: %#v", m.ToCreateRequestMock.defaultExpectation.expectationOrigins.origin, *m.ToCreateRequestMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcToCreateRequest != nil && afterToCreateRequestCounter < 1 {
		m.t.Errorf("Expected call to RepoConverterMock.ToCreateRequest at\n%s", m.funcToCreateRequestOrigin)
	}

	if !m.ToCreateRequestMock.invocationsDone() && afterToCreateRequestCounter > 0 {
		m.t.Errorf("Expected %d calls to RepoConverterMock.ToCreateRequest at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ToCreateRequestMock.expectedInvocations), m.ToCreateRequestMock.expectedInvocationsOrigin, afterToCreateRequestCounter)
	}
}

type mRepoConverterMockToSendMessageRequest struct {
	optional           bool
	mock               *RepoConverterMock
	defaultExpectation *RepoConverterMockToSendMessageRequestExpectation
	expectations       []*RepoConverterMockToSendMessageRequestExpectation

	callArgs []*RepoConverterMockToSendMessageRequestParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepoConverterMockToSendMessageRequestExpectation specifies expectation struct of the RepoConverter.ToSendMessageRequest
type RepoConverterMockToSendMessageRequestExpectation struct {
	mock               *RepoConverterMock
	params             *RepoConverterMockToSendMessageRequestParams
	paramPtrs          *RepoConverterMockToSendMessageRequestParamPtrs
	expectationOrigins RepoConverterMockToSendMessageRequestExpectationOrigins
	results            *RepoConverterMockToSendMessageRequestResults
	returnOrigin       string
	Counter            uint64
}

// RepoConverterMockToSendMessageRequestParams contains parameters of the RepoConverter.ToSendMessageRequest
type RepoConverterMockToSendMessageRequestParams struct {
	req *serviceModel.SendMessageRequest
}

// RepoConverterMockToSendMessageRequestParamPtrs contains pointers to parameters of the RepoConverter.ToSendMessageRequest
type RepoConverterMockToSendMessageRequestParamPtrs struct {
	req **serviceModel.SendMessageRequest
}

// RepoConverterMockToSendMessageRequestResults contains results of the RepoConverter.ToSendMessageRequest
type RepoConverterMockToSendMessageRequestResults struct {
	sp1 *repoModel.SendMessageRequest
}

// RepoConverterMockToSendMessageRequestOrigins contains origins of expectations of the RepoConverter.ToSendMessageRequest
type RepoConverterMockToSendMessageRequestExpectationOrigins struct {
	origin    string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) Optional() *mRepoConverterMockToSendMessageRequest {
	mmToSendMessageRequest.optional = true
	return mmToSendMessageRequest
}

// Expect sets up expected params for RepoConverter.ToSendMessageRequest
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) Expect(req *serviceModel.SendMessageRequest) *mRepoConverterMockToSendMessageRequest {
	if mmToSendMessageRequest.mock.funcToSendMessageRequest != nil {
		mmToSendMessageRequest.mock.t.Fatalf("RepoConverterMock.ToSendMessageRequest mock is already set by Set")
	}

	if mmToSendMessageRequest.defaultExpectation == nil {
		mmToSendMessageRequest.defaultExpectation = &RepoConverterMockToSendMessageRequestExpectation{}
	}

	if mmToSendMessageRequest.defaultExpectation.paramPtrs != nil {
		mmToSendMessageRequest.mock.t.Fatalf("RepoConverterMock.ToSendMessageRequest mock is already set by ExpectParams functions")
	}

	mmToSendMessageRequest.defaultExpectation.params = &RepoConverterMockToSendMessageRequestParams{req}
	mmToSendMessageRequest.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmToSendMessageRequest.expectations {
		if minimock.Equal(e.params, mmToSendMessageRequest.defaultExpectation.params) {
			mmToSendMessageRequest.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmToSendMessageRequest.defaultExpectation.params)
		}
	}

	return mmToSendMessageRequest
}

// ExpectReqParam1 sets up expected param req for RepoConverter.ToSendMessageRequest
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) ExpectReqParam1(req *serviceModel.SendMessageRequest) *mRepoConverterMockToSendMessageRequest {
	if mmToSendMessageRequest.mock.funcToSendMessageRequest != nil {
		mmToSendMessageRequest.mock.t.Fatalf("RepoConverterMock.ToSendMessageRequest mock is already set by Set")
	}

	if mmToSendMessageRequest.defaultExpectation == nil {
		mmToSendMessageRequest.defaultExpectation = &RepoConverterMockToSendMessageRequestExpectation{}
	}

	if mmToSendMessageRequest.defaultExpectation.params != nil {
		mmToSendMessageRequest.mock.t.Fatalf("RepoConverterMock.ToSendMessageRequest mock is already set by Expect")
	}

	if mmToSendMessageRequest.defaultExpectation.paramPtrs == nil {
		mmToSendMessageRequest.defaultExpectation.paramPtrs = &RepoConverterMockToSendMessageRequestParamPtrs{}
	}
	mmToSendMessageRequest.defaultExpectation.paramPtrs.req = &req
	mmToSendMessageRequest.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmToSendMessageRequest
}

// Inspect accepts an inspector function that has same arguments as the RepoConverter.ToSendMessageRequest
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) Inspect(f func(req *serviceModel.SendMessageRequest)) *mRepoConverterMockToSendMessageRequest {
	if mmToSendMessageRequest.mock.inspectFuncToSendMessageRequest != nil {
		mmToSendMessageRequest.mock.t.Fatalf("Inspect function is already set for RepoConverterMock.ToSendMessageRequest")
	}

	mmToSendMessageRequest.mock.inspectFuncToSendMessageRequest = f

	return mmToSendMessageRequest
}

// Return sets up results that will be returned by RepoConverter.ToSendMessageRequest
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) Return(sp1 *repoModel.SendMessageRequest) *RepoConverterMock {
	if mmToSendMessageRequest.mock.funcToSendMessageRequest != nil {
		mmToSendMessageRequest.mock.t.Fatalf("RepoConverterMock.ToSendMessageRequest mock is already set by Set")
	}

	if mmToSendMessageRequest.defaultExpectation == nil {
		mmToSendMessageRequest.defaultExpectation = &RepoConverterMockToSendMessageRequestExpectation{mock: mmToSendMessageRequest.mock}
	}
	mmToSendMessageRequest.defaultExpectation.results = &RepoConverterMockToSendMessageRequestResults{sp1}
	mmToSendMessageRequest.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmToSendMessageRequest.mock
}

// Set uses given function f to mock the RepoConverter.ToSendMessageRequest method
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) Set(f func(req *serviceModel.SendMessageRequest) (sp1 *repoModel.SendMessageRequest)) *RepoConverterMock {
	if mmToSendMessageRequest.defaultExpectation != nil {
		mmToSendMessageRequest.mock.t.Fatalf("Default expectation is already set for the RepoConverter.ToSendMessageRequest method")
	}

	if len(mmToSendMessageRequest.expectations) > 0 {
		mmToSendMessageRequest.mock.t.Fatalf("Some expectations are already set for the RepoConverter.ToSendMessageRequest method")
	}

	mmToSendMessageRequest.mock.funcToSendMessageRequest = f
	mmToSendMessageRequest.mock.funcToSendMessageRequestOrigin = minimock.CallerInfo(1)
	return mmToSendMessageRequest.mock
}

// When sets expectation for the RepoConverter.ToSendMessageRequest which will trigger the result defined by the following
// Then helper
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) When(req *serviceModel.SendMessageRequest) *RepoConverterMockToSendMessageRequestExpectation {
	if mmToSendMessageRequest.mock.funcToSendMessageRequest != nil {
		mmToSendMessageRequest.mock.t.Fatalf("RepoConverterMock.ToSendMessageRequest mock is already set by Set")
	}

	expectation := &RepoConverterMockToSendMessageRequestExpectation{
		mock:               mmToSendMessageRequest.mock,
		params:             &RepoConverterMockToSendMessageRequestParams{req},
		expectationOrigins: RepoConverterMockToSendMessageRequestExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmToSendMessageRequest.expectations = append(mmToSendMessageRequest.expectations, expectation)
	return expectation
}

// Then sets up RepoConverter.ToSendMessageRequest return parameters for the expectation previously defined by the When method
func (e *RepoConverterMockToSendMessageRequestExpectation) Then(sp1 *repoModel.SendMessageRequest) *RepoConverterMock {
	e.results = &RepoConverterMockToSendMessageRequestResults{sp1}
	return e.mock
}

// Times sets number of times RepoConverter.ToSendMessageRequest should be invoked
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) Times(n uint64) *mRepoConverterMockToSendMessageRequest {
	if n == 0 {
		mmToSendMessageRequest.mock.t.Fatalf("Times of RepoConverterMock.ToSendMessageRequest mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmToSendMessageRequest.expectedInvocations, n)
	mmToSendMessageRequest.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmToSendMessageRequest
}

func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) invocationsDone() bool {
	if len(mmToSendMessageRequest.expectations) == 0 && mmToSendMessageRequest.defaultExpectation == nil && mmToSendMessageRequest.mock.funcToSendMessageRequest == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmToSendMessageRequest.mock.afterToSendMessageRequestCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmToSendMessageRequest.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ToSendMessageRequest implements mm_repository.RepoConverter
func (mmToSendMessageRequest *RepoConverterMock) ToSendMessageRequest(req *serviceModel.SendMessageRequest) (sp1 *repoModel.SendMessageRequest) {
	mm_atomic.AddUint64(&mmToSendMessageRequest.beforeToSendMessageRequestCounter, 1)
	defer mm_atomic.AddUint64(&mmToSendMessageRequest.afterToSendMessageRequestCounter, 1)

	mmToSendMessageRequest.t.Helper()

	if mmToSendMessageRequest.inspectFuncToSendMessageRequest != nil {
		mmToSendMessageRequest.inspectFuncToSendMessageRequest(req)
	}

	mm_params := RepoConverterMockToSendMessageRequestParams{req}

	// Record call args
	mmToSendMessageRequest.ToSendMessageRequestMock.mutex.Lock()
	mmToSendMessageRequest.ToSendMessageRequestMock.callArgs = append(mmToSendMessageRequest.ToSendMessageRequestMock.callArgs, &mm_params)
	mmToSendMessageRequest.ToSendMessageRequestMock.mutex.Unlock()

	for _, e := range mmToSendMessageRequest.ToSendMessageRequestMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1
		}
	}

	if mmToSendMessageRequest.ToSendMessageRequestMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmToSendMessageRequest.ToSendMessageRequestMock.defaultExpectation.Counter, 1)
		mm_want := mmToSendMessageRequest.ToSendMessageRequestMock.defaultExpectation.params
		mm_want_ptrs := mmToSendMessageRequest.ToSendMessageRequestMock.defaultExpectation.paramPtrs

		mm_got := RepoConverterMockToSendMessageRequestParams{req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmToSendMessageRequest.t.Errorf("RepoConverterMock.ToSendMessageRequest got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmToSendMessageRequest.ToSendMessageRequestMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmToSendMessageRequest.t.Errorf("RepoConverterMock.ToSendMessageRequest got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmToSendMessageRequest.ToSendMessageRequestMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmToSendMessageRequest.ToSendMessageRequestMock.defaultExpectation.results
		if mm_results == nil {
			mmToSendMessageRequest.t.Fatal("No results are set for the RepoConverterMock.ToSendMessageRequest")
		}
		return (*mm_results).sp1
	}
	if mmToSendMessageRequest.funcToSendMessageRequest != nil {
		return mmToSendMessageRequest.funcToSendMessageRequest(req)
	}
	mmToSendMessageRequest.t.Fatalf("Unexpected call to RepoConverterMock.ToSendMessageRequest. %v", req)
	return
}

// ToSendMessageRequestAfterCounter returns a count of finished RepoConverterMock.ToSendMessageRequest invocations
func (mmToSendMessageRequest *RepoConverterMock) ToSendMessageRequestAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmToSendMessageRequest.afterToSendMessageRequestCounter)
}

// ToSendMessageRequestBeforeCounter returns a count of RepoConverterMock.ToSendMessageRequest invocations
func (mmToSendMessageRequest *RepoConverterMock) ToSendMessageRequestBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmToSendMessageRequest.beforeToSendMessageRequestCounter)
}

// Calls returns a list of arguments used in each call to RepoConverterMock.ToSendMessageRequest.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmToSendMessageRequest *mRepoConverterMockToSendMessageRequest) Calls() []*RepoConverterMockToSendMessageRequestParams {
	mmToSendMessageRequest.mutex.RLock()

	argCopy := make([]*RepoConverterMockToSendMessageRequestParams, len(mmToSendMessageRequest.callArgs))
	copy(argCopy, mmToSendMessageRequest.callArgs)

	mmToSendMessageRequest.mutex.RUnlock()

	return argCopy
}

// MinimockToSendMessageRequestDone returns true if the count of the ToSendMessageRequest invocations corresponds
// the number of defined expectations
func (m *RepoConverterMock) MinimockToSendMessageRequestDone() bool {
	if m.ToSendMessageRequestMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ToSendMessageRequestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ToSendMessageRequestMock.invocationsDone()
}

// MinimockToSendMessageRequestInspect logs each unmet expectation
func (m *RepoConverterMock) MinimockToSendMessageRequestInspect() {
	for _, e := range m.ToSendMessageRequestMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoConverterMock.ToSendMessageRequest at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterToSendMessageRequestCounter := mm_atomic.LoadUint64(&m.afterToSendMessageRequestCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ToSendMessageRequestMock.defaultExpectation != nil && afterToSendMessageRequestCounter < 1 {
		if m.ToSendMessageRequestMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepoConverterMock.ToSendMessageRequest at\n%s", m.ToSendMessageRequestMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepoConverterMock.ToSendMessageRequest at\n%s with params: %#v", m.ToSendMessageRequestMock.defaultExpectation.expectationOrigins.origin, *m.ToSendMessageRequestMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcToSendMessageRequest != nil && afterToSendMessageRequestCounter < 1 {
		m.t.Errorf("Expected call to RepoConverterMock.ToSendMessageRequest at\n%s", m.funcToSendMessageRequestOrigin)
	}

	if !m.ToSendMessageRequestMock.invocationsDone() && afterToSendMessageRequestCounter > 0 {
		m.t.Errorf("Expected %d calls to RepoConverterMock.ToSendMessageRequest at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ToSendMessageRequestMock.expectedInvocations), m.ToSendMessageRequestMock.expectedInvocationsOrigin, afterToSendMessageRequestCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepoConverterMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockToCreateRequestInspect()

			m.MinimockToSendMessageRequestInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepoConverterMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepoConverterMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockToCreateRequestDone() &&
		m.MinimockToSendMessageRequestDone()
}
